### ISSUE TITLE
No output shown while thinking

### ISSUE THREAD

**Issue by GrahamCCRL** [kelseyde/calvin-chess-engine#1]
I'm using ChessGUI.
Calvin will move after about 30 seconds, and will continue to make moves, but shows no output infotmation.
Also, is it possible to set Calven to use 256mb hash and 1 core ?

Graham (CCRL)

**Comment by kelseyde** [comment]
Hello @GrahamCCRL ,

My apologies for taking so long to reply in the forum. I haven't got around to implementing the last touches to make Calvin CCRL-compliant yet. I'll have a go at it next week. 

Regarding your comments:

1. I haven't implemented logging info to UCI yet. Right now I simply respond with the best move. I'll add it to the list.
2. It's also not possible to configure the hash size or cores via UCI yet, but I can add that in too.

Are there any other CCRL requirements I should be aware of ? I've read that opening book/tablebases should be disabled - that's not a problem, as I haven't implemented either of those yet :) 

Regards,
Dan

**Comment by GrahamCCRL** [comment]
I allow tablebases use. :-)

Graham.

**Comment by kelseyde** [comment]
Hello @GrahamCCRL ,

The latest Calvin release 3.0.0 contains some UCI compatibility improvements. Now hash size and number of threads are configurable via UCI. Startup time is also improved (I ditched Spring Boot and now run as a pure Java application, much faster on startup...) 

Next up is info output while thinking. 

Kind regards,
Dan

**Comment by kelseyde** [comment]
Hello @GrahamCCRL ,

This issue is finally resolved with the latest release of [Calvin 3.4.0](https://github.com/kelseyde/calvin-chess-engine/releases/tag/3.4.0)! 

Calvin now outputs basic info (depth, score, nodes, time, nps, pv) while thinking :)

Regards,
Dan

**Comment by GrahamCCRL** [comment]
Thanks. :-)
