### ISSUE TITLE
UCI protocol

### ISSUE THREAD

**Issue by AlexBrunetti** [kelseyde/calvin-chess-engine#2]
Hi,
UCI is stateless, the engine should evaluate the specified position.

```
...
bestmove g1f3
position startpos moves d2d4 e7e5
go wtime 50000 winc 1000 btime 50000 binc 1000
bestmove f3e5
```
After the "position" command, there's not a Knight on f3.

```
go wtime 50000 winc 1000 btime 50000 binc 1000
bestmove d7d6
go wtime 50000 winc 1000 btime 50000 binc 1000
bestmove e5f3
go wtime 50000 winc 1000 btime 50000 binc 1000
bestmove f8e7
go wtime 50000 winc 1000 btime 50000 binc 1000
bestmove d2d4
```

The engine is "playing" the moves; well, the position is always the last one sent with "position"; after every "go" I'd expect the same bestmove.

Alex

**Comment by kelseyde** [comment]
Hello @AlexBrunetti , thank you for raising this issue. I'm currently working on a major release of Calvin concerning UCI-compatibility, in order to submit it to the CCRL rankings. I will include this fix in the release.

**Comment by kelseyde** [comment]
Hi @AlexBrunetti , the latest Calvin release 3.0.0 contains the bugfix for this issue.
